definitions:
  controllers.HealthResponse:
    properties:
      components:
        additionalProperties:
          $ref: '#/definitions/controllers.HealthStatus'
        type: object
      status:
        type: string
    type: object
  controllers.HealthStatus:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /management/health/liveness:
    get:
      description: Get the liveness status of the service
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/controllers.HealthResponse'
      summary: Get the liveness status
  /management/health/readiness:
    get:
      description: Get the readiness status of the service
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/controllers.HealthResponse'
      summary: Get the readiness status
swagger: "2.0"
